apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
data:
  AWS_REGION: "us-east-1"
  QUEUE_SQS_BASE_URL: "https://sqs.us-east-1.amazonaws.com/<ACCOUNT_ID>/"
  ASPNETCORE_URLS: "http://+:8081"
  ASPNETCORE_ENVIRONMENT: "Production"
