apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
data:
  AWS_SERVICE_URL: "http://host.docker.internal:4566"
  QUEUE_SQS_BASE_URL: "http://host.docker.internal:4566/000000000000/"
  ASPNETCORE_URLS: "http://+:8081"
  ASPNETCORE_ENVIRONMENT: "Production"