apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/users-api:latest
        ports:
          - containerPort: 8081
        envFrom:
          - configMapRef:
              name: users-api-config
          - secretRef:
              name: users-api-secret
        volumeMounts:
        - name: users-data
          mountPath: /data
      volumes:
      - name: users-data
        persistentVolumeClaim:
          claimName: users-api-pvc