apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
stringData:
  AWS_USER: "teste"
  AWS_PASSWORD: "teste"
  DATABASE_CONNECTION: Data Source=/data/users.db
  JWT_SECRET: GAMESSTORE_SECRET_KEY_1234567890