apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
type: Opaque
stringData:
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  DATABASE_CONNECTION: Data Source=/data/users.db
  JWT_SECRET: GAMESSTORE_SECRET_KEY_1234567890