apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users-api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: users-api-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .awsAccessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .awsSecretAccessKey }}"
        JWT_SECRET: "{{ .jwtSecret }}"
        DATABASE_CONNECTION: "Data Source=/data/users.db"
  data:
    - secretKey: awsAccessKeyId
      remoteRef:
        key: fcg/app-aws-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: awsSecretAccessKey
      remoteRef:
        key: fcg/app-aws-credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: jwtSecret
      remoteRef:
        key: fcg/jwt
        property: JWT_SECRET
